//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Captain.UI {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Captain.UI.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap AcrylicNoiseTexture {
            get {
                object obj = ResourceManager.GetObject("AcrylicNoiseTexture", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ClipperCorners {
            get {
                object obj = ResourceManager.GetObject("ClipperCorners", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ClipperPickRegion {
            get {
                object obj = ResourceManager.GetObject("ClipperPickRegion", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ClipperPickWindow {
            get {
                object obj = ResourceManager.GetObject("ClipperPickWindow", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture2D g_Texture : register(t0);
        ///SamplerState g_Sampler : register(s0);
        ///
        ///struct VertexShaderInput {
        ///  float4 vPosition : POSITION;
        ///  float2 vTexCoord : TEXCOORD;
        ///};
        ///
        ///struct PixelShaderInput {
        ///  float4 vPosition : SV_POSITION;
        ///  float2 vTexCoord : TEXCOORD;
        ///};
        ///
        ///PixelShaderInput VertexShaderMain(VertexShaderInput input) {
        ///  PixelShaderInput output = (PixelShaderInput)0;
        ///  output.vPosition = input.vPosition;
        ///  output.vTexCoord = -input.vTexCoord + float4(0.5, 0.5, 0.5, 0.5);
        ///
        ///  return outp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HudOverlayShader {
            get {
                return ResourceManager.GetString("HudOverlayShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Invalid {
            get {
                object obj = ResourceManager.GetObject("Invalid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Normal {
            get {
                object obj = ResourceManager.GetObject("Normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SnackBarClose {
            get {
                object obj = ResourceManager.GetObject("SnackBarClose", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SnackBarGrip {
            get {
                object obj = ResourceManager.GetObject("SnackBarGrip", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SnackBarMute {
            get {
                object obj = ResourceManager.GetObject("SnackBarMute", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SnackBarOptions {
            get {
                object obj = ResourceManager.GetObject("SnackBarOptions", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SnackBarPause {
            get {
                object obj = ResourceManager.GetObject("SnackBarPause", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SnackBarRecord {
            get {
                object obj = ResourceManager.GetObject("SnackBarRecord", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SnackBarResume {
            get {
                object obj = ResourceManager.GetObject("SnackBarResume", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SnackBarScreenshot {
            get {
                object obj = ResourceManager.GetObject("SnackBarScreenshot", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SnackBarStop {
            get {
                object obj = ResourceManager.GetObject("SnackBarStop", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SnackBarUnmute {
            get {
                object obj = ResourceManager.GetObject("SnackBarUnmute", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap TidbitError {
            get {
                object obj = ResourceManager.GetObject("TidbitError", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap TidbitInfo {
            get {
                object obj = ResourceManager.GetObject("TidbitInfo", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap TidbitOk {
            get {
                object obj = ResourceManager.GetObject("TidbitOk", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap TidbitWarning {
            get {
                object obj = ResourceManager.GetObject("TidbitWarning", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Window {
            get {
                object obj = ResourceManager.GetObject("Window", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
